version: 2.1

jobs:
  build-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run test"
          command: "npm test"

workflows:
  build-test-workflow:
    jobs:
      - build-test
